port: PORT
cache_base_url: CACHE_BASE_URL
keystore: KEYSTORE
arweave:
  host: ARWEAVE_HOST
  port: ARWEAVE_PORT
  protocol: ARWEAVE_PROTOCOL
aws:
  host: AWS_HOST
  key: AWS_KEY
  secret: AWS_SECRET
  bucket: AWS_BUCKET
