port: PORT
keystore: KEYSTORE
arweave:
  host: ARWEAVE_HOST
  port: ARWEAVE_PORT
  protocol: ARWEAVE_PROTOCOL

s3:
  protocol: S3_PROTOCOL
  host: S3_HOST
  port: S3_PORT
  key: S3_KEY_FILE
  secret: S3_SECRET_FILE
  bucket: S3_BUCKET
