port: PORT
keystore: KEYSTORE
testmode: TESTMODE
arweave:
  host: ARWEAVE_HOST
  port: ARWEAVE_PORT
  protocol: ARWEAVE_PROTOCOL

s3:
  protocol: S3_PROTOCOL
  host: S3_HOST
  port: S3_PORT
  key: S3_KEY
  secret: S3_SECRET
  bucket: S3_BUCKET
