port: PORT
testmode: TESTMODE
arweave:
  default_node_host: ARWEAVE_HOST
  default_node_port: ARWEAVE_PORT
  default_node_protocol: ARWEAVE_PROTOCOL
  key: ARWEAVE_KEY

s3:
  protocol: S3_PROTOCOL
  host: S3_HOST
  port: S3_PORT
  key: S3_KEY
  secret: S3_SECRET
  bucket: S3_BUCKET
