port: 80
keystore: '../keystore/key.json'
arweave:
  host: arweave.net
  port: 443
  protocol: https

s3:
  protocol: https
  host: fra1.digitaloceanspaces.com
  port: 443
  key:
  secret:
  bucket: pointdisk
