port: 80
testmode: 0
arweave:
  default_node_host: arweave.net
  default_node_port: 443
  default_node_protocol: https
  timeout: 20000
  worker_delay: 500
  default_node_health_check_interval: 5000
  logging: true
  key: ''

s3:
  protocol: https
  host: fra1.digitaloceanspaces.com
  port: 443
  key: ''
  secret: ''
  bucket: pointdisk
